/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pizzeria.java
 *
 * Created on Jan 1, 2022, 6:29:39 PM
 */

package foodordering;


import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author zedso
 */
public class Pizzeria extends javax.swing.JFrame {

    double Price_Fries = 150;
    double Price_Soup = 320;
    double Price_Bisque = 200;
    double Price_Grill = 240;
    double Price_Burata = 150;
    double Price_Nicoise = 220;
    double Price_Josper = 190;
    double Price_Pepper = 300;
    double Price_Napolitana = 350;
    double Price_Margarita = 250;
    double Price_Creamy = 90;
    double Price_Mayo = 40;
    double Price_Cola = 100;
    double Price_Pepsi = 100;
    double Price_Fanta = 100;
    double Price_Orange = 150;
    double Tax_Rate = 30;

    double iTax,iTotal,iSubTotal,iChange,iCost;

    double[] itemcost = new double[18];



    /** Creates new form Pizzeria */
    public Pizzeria() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Soup = new javax.swing.JTextField();
        Bisque = new javax.swing.JTextField();
        ChkSoup = new javax.swing.JCheckBox();
        ChkBisque = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        ChkFries = new javax.swing.JCheckBox();
        ChkCreamy = new javax.swing.JCheckBox();
        ChkMayo = new javax.swing.JCheckBox();
        Fries = new javax.swing.JTextField();
        Creamy = new javax.swing.JTextField();
        Mayo = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        ChkGrill = new javax.swing.JCheckBox();
        ChkBurata = new javax.swing.JCheckBox();
        ChkNicoise = new javax.swing.JCheckBox();
        ChkJosper = new javax.swing.JCheckBox();
        Grill = new javax.swing.JTextField();
        Burata = new javax.swing.JTextField();
        Nicoise = new javax.swing.JTextField();
        Josper = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ChkCola = new javax.swing.JCheckBox();
        ChkPepsi = new javax.swing.JCheckBox();
        ChkFanta = new javax.swing.JCheckBox();
        ChkOrange = new javax.swing.JCheckBox();
        Cola = new javax.swing.JTextField();
        Pepsi = new javax.swing.JTextField();
        Fanta = new javax.swing.JTextField();
        Orange = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        ChkPepper = new javax.swing.JCheckBox();
        ChkNapolitana = new javax.swing.JCheckBox();
        ChkMargarita = new javax.swing.JCheckBox();
        Pepper = new javax.swing.JTextField();
        Napolitana = new javax.swing.JTextField();
        Margarita = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        cmbPaymentMethod = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        Cash = new javax.swing.JTextField();
        bTotal = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTax = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JTextField();
        LblTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Change = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));
        jPanel5.setForeground(new java.awt.Color(204, 102, 0));
        jPanel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel5AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Soup.setBackground(new java.awt.Color(255, 153, 153));
        Soup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Soup.setText("0");
        Soup.setEnabled(false);
        Soup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoupActionPerformed(evt);
            }
        });
        Soup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SoupKeyTyped(evt);
            }
        });
        jPanel5.add(Soup, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 109, -1));

        Bisque.setBackground(new java.awt.Color(255, 153, 153));
        Bisque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Bisque.setText("0");
        Bisque.setEnabled(false);
        Bisque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BisqueActionPerformed(evt);
            }
        });
        Bisque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BisqueKeyTyped(evt);
            }
        });
        jPanel5.add(Bisque, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 109, -1));

        ChkSoup.setBackground(new java.awt.Color(255, 153, 153));
        ChkSoup.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkSoup.setText("Minestrone Soup - 320");
        ChkSoup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkSoupActionPerformed(evt);
            }
        });
        jPanel5.add(ChkSoup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        ChkBisque.setBackground(new java.awt.Color(255, 153, 153));
        ChkBisque.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkBisque.setText("Langoustine Bisque - 200");
        ChkBisque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkBisqueActionPerformed(evt);
            }
        });
        jPanel5.add(ChkBisque, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel25.setBackground(new java.awt.Color(255, 153, 153));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel25.setText("Soups and Additions");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        ChkFries.setBackground(new java.awt.Color(255, 153, 153));
        ChkFries.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkFries.setText("French Fries - 150");
        ChkFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkFriesActionPerformed(evt);
            }
        });
        jPanel5.add(ChkFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        ChkCreamy.setBackground(new java.awt.Color(255, 153, 153));
        ChkCreamy.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkCreamy.setText("Creamy Spinach - 90");
        ChkCreamy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkCreamyActionPerformed(evt);
            }
        });
        jPanel5.add(ChkCreamy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        ChkMayo.setBackground(new java.awt.Color(255, 153, 153));
        ChkMayo.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkMayo.setText("Chilli Mayonnaise - 40");
        ChkMayo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkMayoActionPerformed(evt);
            }
        });
        jPanel5.add(ChkMayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        Fries.setBackground(new java.awt.Color(255, 153, 153));
        Fries.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fries.setText("0");
        Fries.setEnabled(false);
        Fries.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FriesKeyTyped(evt);
            }
        });
        jPanel5.add(Fries, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 110, -1));

        Creamy.setBackground(new java.awt.Color(255, 153, 153));
        Creamy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Creamy.setText("0");
        Creamy.setEnabled(false);
        Creamy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CreamyKeyTyped(evt);
            }
        });
        jPanel5.add(Creamy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 110, -1));

        Mayo.setBackground(new java.awt.Color(255, 153, 153));
        Mayo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Mayo.setText("0");
        Mayo.setEnabled(false);
        Mayo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MayoKeyTyped(evt);
            }
        });
        jPanel5.add(Mayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 110, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 432, 261));

        jPanel7.setBackground(new java.awt.Color(255, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChkGrill.setBackground(new java.awt.Color(255, 153, 153));
        ChkGrill.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkGrill.setText("Grilled Vegetable - 240");
        ChkGrill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkGrillActionPerformed(evt);
            }
        });
        jPanel7.add(ChkGrill, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        ChkBurata.setBackground(new java.awt.Color(255, 153, 153));
        ChkBurata.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkBurata.setText("Burata Salad - 150");
        ChkBurata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkBurataActionPerformed(evt);
            }
        });
        jPanel7.add(ChkBurata, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        ChkNicoise.setBackground(new java.awt.Color(255, 153, 153));
        ChkNicoise.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkNicoise.setText("Nicoise Salad - 220");
        ChkNicoise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkNicoiseActionPerformed(evt);
            }
        });
        jPanel7.add(ChkNicoise, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        ChkJosper.setBackground(new java.awt.Color(255, 153, 153));
        ChkJosper.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkJosper.setText("Josper Salmon - 190");
        ChkJosper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkJosperActionPerformed(evt);
            }
        });
        jPanel7.add(ChkJosper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        Grill.setBackground(new java.awt.Color(255, 153, 153));
        Grill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Grill.setText("0");
        Grill.setEnabled(false);
        Grill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GrillKeyTyped(evt);
            }
        });
        jPanel7.add(Grill, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 84, -1));

        Burata.setBackground(new java.awt.Color(255, 153, 153));
        Burata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Burata.setText("0");
        Burata.setEnabled(false);
        Burata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BurataKeyTyped(evt);
            }
        });
        jPanel7.add(Burata, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 84, -1));

        Nicoise.setBackground(new java.awt.Color(255, 153, 153));
        Nicoise.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nicoise.setText("0");
        Nicoise.setEnabled(false);
        Nicoise.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NicoiseKeyTyped(evt);
            }
        });
        jPanel7.add(Nicoise, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 84, -1));

        Josper.setBackground(new java.awt.Color(255, 153, 153));
        Josper.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Josper.setText("0");
        Josper.setEnabled(false);
        Josper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JosperKeyTyped(evt);
            }
        });
        jPanel7.add(Josper, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 84, -1));

        jLabel67.setBackground(new java.awt.Color(255, 153, 153));
        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel67.setText("Salads");
        jPanel7.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 432, 196));

        jPanel8.setBackground(new java.awt.Color(255, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChkCola.setBackground(new java.awt.Color(255, 153, 153));
        ChkCola.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkCola.setText("Coca Cola - 100");
        ChkCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkColaActionPerformed(evt);
            }
        });
        jPanel8.add(ChkCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, -1));

        ChkPepsi.setBackground(new java.awt.Color(255, 153, 153));
        ChkPepsi.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkPepsi.setText("Pepsi - 100");
        ChkPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkPepsiActionPerformed(evt);
            }
        });
        jPanel8.add(ChkPepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 69, -1, -1));

        ChkFanta.setBackground(new java.awt.Color(255, 153, 153));
        ChkFanta.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkFanta.setText("Fanta - 100");
        ChkFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkFantaActionPerformed(evt);
            }
        });
        jPanel8.add(ChkFanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, 23));

        ChkOrange.setBackground(new java.awt.Color(255, 153, 153));
        ChkOrange.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkOrange.setText("Orange Juice - 150");
        ChkOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkOrangeActionPerformed(evt);
            }
        });
        jPanel8.add(ChkOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 154, -1, -1));

        Cola.setBackground(new java.awt.Color(255, 153, 153));
        Cola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cola.setText("0");
        Cola.setEnabled(false);
        Cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaActionPerformed(evt);
            }
        });
        Cola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ColaKeyTyped(evt);
            }
        });
        jPanel8.add(Cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 30, 106, -1));

        Pepsi.setBackground(new java.awt.Color(255, 153, 153));
        Pepsi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pepsi.setText("0");
        Pepsi.setEnabled(false);
        Pepsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PepsiKeyTyped(evt);
            }
        });
        jPanel8.add(Pepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 73, 106, -1));

        Fanta.setBackground(new java.awt.Color(255, 153, 153));
        Fanta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fanta.setText("0");
        Fanta.setEnabled(false);
        Fanta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FantaKeyTyped(evt);
            }
        });
        jPanel8.add(Fanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 116, 106, -1));

        Orange.setBackground(new java.awt.Color(255, 153, 153));
        Orange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Orange.setText("0");
        Orange.setEnabled(false);
        Orange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OrangeKeyTyped(evt);
            }
        });
        jPanel8.add(Orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 158, 106, -1));

        jLabel26.setBackground(new java.awt.Color(255, 153, 153));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel26.setText("Drinks");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 310, 200));

        jPanel9.setBackground(new java.awt.Color(255, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChkPepper.setBackground(new java.awt.Color(255, 153, 153));
        ChkPepper.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkPepper.setText("Pepperoni Pizza - 300");
        ChkPepper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkPepperActionPerformed(evt);
            }
        });
        jPanel9.add(ChkPepper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        ChkNapolitana.setBackground(new java.awt.Color(255, 153, 153));
        ChkNapolitana.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkNapolitana.setText("Napolitana Pizza - 350");
        ChkNapolitana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkNapolitanaActionPerformed(evt);
            }
        });
        jPanel9.add(ChkNapolitana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 23));

        ChkMargarita.setBackground(new java.awt.Color(255, 153, 153));
        ChkMargarita.setFont(new java.awt.Font("Tahoma", 1, 14));
        ChkMargarita.setText("Margarita Pizza - 250");
        ChkMargarita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkMargaritaActionPerformed(evt);
            }
        });
        jPanel9.add(ChkMargarita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        Pepper.setBackground(new java.awt.Color(255, 153, 153));
        Pepper.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pepper.setText("0");
        Pepper.setEnabled(false);
        Pepper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PepperKeyTyped(evt);
            }
        });
        jPanel9.add(Pepper, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 87, -1));

        Napolitana.setBackground(new java.awt.Color(255, 153, 153));
        Napolitana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Napolitana.setText("0");
        Napolitana.setEnabled(false);
        Napolitana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NapolitanaKeyTyped(evt);
            }
        });
        jPanel9.add(Napolitana, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 87, -1));

        Margarita.setBackground(new java.awt.Color(255, 153, 153));
        Margarita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Margarita.setText("0");
        Margarita.setEnabled(false);
        Margarita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MargaritaKeyTyped(evt);
            }
        });
        jPanel9.add(Margarita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 87, -1));

        jLabel66.setBackground(new java.awt.Color(255, 153, 153));
        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel66.setText("Pizza");
        jPanel9.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 432, 170));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 27));
        jLabel1.setText("Restaurant Speciality");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 29));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel34.setText("Please Select Your Order");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 176, 25));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodordering/icons/Screenshot_8.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodordering/icons/Screenshot_9.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jPanel10.setBackground(new java.awt.Color(255, 153, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbPaymentMethod.setFont(new java.awt.Font("Tahoma", 1, 18));
        cmbPaymentMethod.setText("Payment Method");
        jPanel10.add(cmbPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card" }));
        jPanel10.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        Cash.setFont(new java.awt.Font("Tahoma", 0, 18));
        Cash.setText("0");
        jPanel10.add(Cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 75, -1));

        bTotal.setBackground(new java.awt.Color(255, 153, 153));
        bTotal.setFont(new java.awt.Font("Tahoma", 1, 18));
        bTotal.setText("Total");
        bTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTotalActionPerformed(evt);
            }
        });
        jPanel10.add(bTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 310, 160));

        jPanel11.setBackground(new java.awt.Color(255, 153, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(255, 153, 153));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Tax");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTax.setBackground(new java.awt.Color(255, 153, 153));
        jTax.setFont(new java.awt.Font("Tahoma", 0, 18));
        jPanel11.add(jTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 143, -1));

        jLabel33.setBackground(new java.awt.Color(255, 153, 153));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Subtotal");
        jPanel11.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jlblSubTotal.setBackground(new java.awt.Color(255, 153, 153));
        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 0, 18));
        jPanel11.add(jlblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, -1));

        LblTotal.setBackground(new java.awt.Color(255, 153, 153));
        LblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblTotal.setText("Total");
        jPanel11.add(LblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jlblTotal.setBackground(new java.awt.Color(255, 153, 153));
        jlblTotal.setFont(new java.awt.Font("Tahoma", 0, 18));
        jlblTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblTotalActionPerformed(evt);
            }
        });
        jPanel11.add(jlblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 143, -1));

        jLabel23.setBackground(new java.awt.Color(255, 153, 153));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Change");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        Change.setBackground(new java.awt.Color(255, 153, 153));
        Change.setFont(new java.awt.Font("Tahoma", 0, 18));
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });
        jPanel11.add(Change, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 143, -1));

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        btnReset.setBackground(new java.awt.Color(255, 153, 153));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel11.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 310, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoupActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SoupActionPerformed

    private void jPanel5AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel5AncestorMoved
        // TODO add your handling code here:
}//GEN-LAST:event_jPanel5AncestorMoved

    private void ChkSoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkSoupActionPerformed
if (ChkSoup.isSelected())
      {
          Soup.setEnabled(true);
          Soup.requestFocus();
          Soup.setText(null);
      }
 else
      {
          Soup.setEnabled(false);
          Soup.setText("0");
 }          // TODO add your handling code here:
    }//GEN-LAST:event_ChkSoupActionPerformed

    private void ColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColaActionPerformed

    private void jlblTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblTotalActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jlblTotalActionPerformed

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ChangeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTotalActionPerformed
itemcost[0] = Double.parseDouble(Fries.getText()) * Price_Fries;
 itemcost[1] = Double.parseDouble(Soup.getText()) *    Price_Soup ;
   itemcost[2] = Double.parseDouble(Bisque.getText()) *  Price_Bisque;
  itemcost[3] = Double.parseDouble(Grill.getText()) *  Price_Grill ;
   itemcost[4] = Double.parseDouble(Burata.getText()) *  Price_Burata ;
   itemcost[5] = Double.parseDouble(Nicoise.getText()) *  Price_Nicoise ;
   itemcost[6] = Double.parseDouble(Josper.getText()) *  Price_Josper;
   itemcost[7] = Double.parseDouble(Pepper.getText()) *  Price_Pepper ;
   itemcost[8] = Double.parseDouble(Napolitana.getText()) *  Price_Napolitana;
   itemcost[9] = Double.parseDouble(Margarita.getText()) *  Price_Margarita ;
   itemcost[10] = Double.parseDouble(Creamy.getText()) *  Price_Creamy;
   itemcost[11] = Double.parseDouble(Mayo.getText()) *  Price_Mayo ;
   itemcost[12] = Double.parseDouble(Cola.getText()) *  Price_Cola ;
   itemcost[13] = Double.parseDouble(Pepsi.getText()) *  Price_Pepsi ;
   itemcost[14] = Double.parseDouble(Fanta.getText()) *  Price_Fanta;
   itemcost[15] = Double.parseDouble(Orange.getText()) *  Price_Orange;

   iChange = Double.parseDouble(Cash.getText());

  String PaymentMethod = (String)jComboBox1.getSelectedItem();
if (PaymentMethod == "Cash")
{
  iSubTotal = itemcost[0] + itemcost[1] + itemcost[2] + itemcost[3] +
          itemcost[4] + itemcost[5] + itemcost[6] + itemcost[7] +
          itemcost[8] + itemcost[9] + itemcost[10] + itemcost[11]+
          itemcost[12] + itemcost[13] + itemcost[14] + itemcost[15];
  iTax= (iSubTotal * Tax_Rate) / 100 ;

  if (iChange>=iSubTotal)
  {
      iTax = (iSubTotal * Tax_Rate)/100;

      String uTax = String.format("$%.2f", iTax );
      jTax.setText(uTax);

      String uSubTotal = String.format("$%.2f",iSubTotal);
      jlblSubTotal.setText(uSubTotal);

      String aTotal=String.format("$%.2f",iSubTotal + iTax);
      jlblTotal.setText(String.valueOf(aTotal));
      String uChange = String.format("$%.2f", iChange - iSubTotal - iTax);
      Change.setText(uChange);

        }
    else
    {
        JOptionPane.showMessageDialog(null,"Not Enough Amount of Money Entered. Please Try Again.", "Restaurant Speciality", JOptionPane.OK_OPTION);
 }
        }
else if (PaymentMethod == "Credit Card")
    {
        iSubTotal = itemcost[0] + itemcost[1] + itemcost[2] + itemcost[3] + itemcost[4]+ itemcost[5]
            + itemcost[6] + itemcost[7] + itemcost[8] + itemcost[9] + itemcost[10] + itemcost[11] + itemcost[12] + itemcost[13] + itemcost[14]+
            itemcost[15];

    iTax = ( iSubTotal * Tax_Rate)/100;

   String cTax = String.format("$%.2f", iTax);
    jTax.setText(cTax);

    String cSubTotal = String.format("$%.2f", iSubTotal);
    jlblSubTotal.setText(cSubTotal);

    double uTotal = new TotalClass().getTotal();

    String cTotal = String.format("$%.2f", iSubTotal + iTax);
    jlblTotal.setText(String.valueOf(cTotal));



    String cChange = String.format("$%.2f", iChange - iSubTotal - iTax);
 Change.setText(cChange);

 }




            // TODO add your handling code here:
    }//GEN-LAST:event_bTotalActionPerformed

    private void ChkFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkFriesActionPerformed
if (ChkFries.isSelected())
      {
          Fries.setEnabled(true);
          Fries.requestFocus();
          Fries.setText(null);
      }
 else
      {
          Fries.setEnabled(false);
        Fries.setText("0");
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkFriesActionPerformed

    private void ChkBisqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkBisqueActionPerformed
if (ChkBisque.isSelected())
      {
          Bisque.setEnabled(true);
          Bisque.requestFocus();
          Bisque.setText(null);
      }
 else
      {
          Bisque.setEnabled(false);
          Bisque.setText("0");
 }          // TODO add your handling code here:
    }//GEN-LAST:event_ChkBisqueActionPerformed

    private void ChkGrillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkGrillActionPerformed
if (ChkGrill.isSelected())
      {
          Grill.setEnabled(true);
          Grill.requestFocus();
          Grill.setText(null);
      }
 else
      {
          Grill.setEnabled(false);
          Grill.setText("0");
 }          // TODO add your handling code here:
    }//GEN-LAST:event_ChkGrillActionPerformed

    private void ChkBurataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkBurataActionPerformed
if (ChkBurata.isSelected())
      {
          Burata.setEnabled(true);
          Burata.requestFocus();
          Burata.setText(null);
      }
 else
      {
          Burata.setEnabled(false);
          Burata.setText("0");
 }          // TODO add your handling code here:
    }//GEN-LAST:event_ChkBurataActionPerformed

    private void ChkNicoiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkNicoiseActionPerformed
if (ChkNicoise.isSelected())
      {
          Nicoise.setEnabled(true);
          Nicoise.requestFocus();
          Nicoise.setText(null);
      }
 else
      {
          Nicoise.setEnabled(false);
          Nicoise.setText("0");
 }          // TODO add your handling code here:
    }//GEN-LAST:event_ChkNicoiseActionPerformed

    private void ChkJosperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkJosperActionPerformed
     if (ChkJosper.isSelected())
      {
          Josper.setEnabled(true);
          Josper.requestFocus();
          Josper.setText(null);
      }
 else
      {
          Josper.setEnabled(false);
          Josper.setText("0");
 }   // TODO add your handling code here:
    }//GEN-LAST:event_ChkJosperActionPerformed

    private void ChkPepperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkPepperActionPerformed
if (ChkPepper.isSelected())
      {
          Pepper.setEnabled(true);
          Pepper.requestFocus();
          Pepper.setText(null);
      }
 else
      {
          Pepper.setEnabled(false);
          Pepper.setText("0");
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkPepperActionPerformed

    private void ChkNapolitanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkNapolitanaActionPerformed
if (ChkNapolitana.isSelected())
      {
          Napolitana.setEnabled(true);
          Napolitana.requestFocus();
          Napolitana.setText(null);
      }
 else
      {
          Napolitana.setEnabled(false);
          Napolitana.setText("0");
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkNapolitanaActionPerformed

    private void ChkMargaritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkMargaritaActionPerformed
if (ChkMargarita.isSelected())
      {
          Margarita.setEnabled(true);
          Margarita.requestFocus();
          Margarita.setText(null);
      }
 else
      {
          Margarita.setEnabled(false);
          Margarita.setText("0");
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkMargaritaActionPerformed

    private void ChkCreamyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkCreamyActionPerformed
if (ChkCreamy.isSelected())
      {
          Creamy.setEnabled(true);
          Creamy.requestFocus();
          Creamy.setText(null);
      }
 else
      {
          Creamy.setEnabled(false);
          Creamy.setText("0");
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkCreamyActionPerformed

    private void ChkMayoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkMayoActionPerformed
if (ChkMayo.isSelected())
      {
          Mayo.setEnabled(true);
          Mayo.requestFocus();
          Mayo.setText(null);
      }
 else
      {
          Mayo.setEnabled(false);
          Mayo.setText("0");
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkMayoActionPerformed

    private void ChkColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkColaActionPerformed
if (ChkCola.isSelected())
      {
          Cola.setEnabled(true);
          Cola.requestFocus();
          Cola.setText(null);
      }
 else
      {
          Cola.setEnabled(false);
          Cola.setText("0");
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkColaActionPerformed

    private void ChkPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkPepsiActionPerformed
if (ChkPepsi.isSelected())
      {
          Pepsi.setEnabled(true);
          Pepsi.requestFocus();
          Pepsi.setText(null);
      }
 else
      {
          Pepsi.setEnabled(false);
          Pepsi.setText("0");
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkPepsiActionPerformed

    private void ChkFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkFantaActionPerformed
if (ChkFanta.isSelected())
      {
          Fanta.setEnabled(true);
          Fanta.requestFocus();
          Fanta.setText(null);
      }
 else
      {
          Fanta.setEnabled(false);
          Fanta.setText("0");
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkFantaActionPerformed

    private void ChkOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkOrangeActionPerformed
    if (ChkOrange.isSelected())
      {
          Orange.setEnabled(true);
          Orange.requestFocus();
          Orange.setText(null);
      }
 else
      {
          Orange.setEnabled(false);
          Orange.setText("0");
 }    // TODO add your handling code here:
    }//GEN-LAST:event_ChkOrangeActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
Cash.setText(null);
Change.setText(null);
jTax.setText(null);
jlblSubTotal.setText(null);
jlblTotal.setText(null);

                //========================
Cola.setEnabled(false);
        Fries.setEnabled(false);
        Fanta.setEnabled(false);
        Pepsi.setEnabled(false);
                Burata.setEnabled(false);
                Nicoise.setEnabled(false);
                Napolitana.setEnabled(false);
                Margarita.setEnabled(false);
                Creamy.setEnabled(false);
                Mayo.setEnabled(false);
                Grill.setEnabled(false);
                Josper.setEnabled(false);
                Pepper.setEnabled(false);
                Soup.setEnabled(false);
                Bisque.setEnabled(false);
                Orange.setEnabled(false);

                //=======================
                Cola.setText("0");
        Fries.setText("0");
        Fanta.setText("0");
        Pepsi.setText("0");
                Burata.setText("0");
                Nicoise.setText("0");
                Napolitana.setText("0");
                Margarita.setText("0");
                Mayo.setText("0");
                Creamy.setText("0");
                Josper.setText("0");
                Pepper.setText("0");
                Soup.setText("0");
                Bisque.setText("0");
                Grill.setText("0");
                Orange.setText("0");

                //=======================
         ChkSoup.setSelected(false);
         ChkBisque.setSelected(false);
         ChkGrill.setSelected(false);
         ChkFries.setSelected(false);
         ChkCreamy.setSelected(false);
         ChkMayo.setSelected(false);
         ChkBurata.setSelected(false);
         ChkNicoise.setSelected(false);
         ChkJosper.setSelected(false);
         ChkCola.setSelected(false);
         ChkPepsi.setSelected(false);
         ChkFanta.setSelected(false);
         ChkOrange.setSelected(false);
         ChkPepper.setSelected(false);
         ChkNapolitana.setSelected(false);
         ChkMargarita.setSelected(false);

                // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void SoupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoupKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_SoupKeyTyped

    private void BisqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BisqueKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BisqueKeyTyped

    private void GrillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrillKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_GrillKeyTyped

    private void BurataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BurataKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BurataKeyTyped

    private void NicoiseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NicoiseKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_NicoiseKeyTyped

    private void JosperKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JosperKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_JosperKeyTyped

    private void PepperKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PepperKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_PepperKeyTyped

    private void NapolitanaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NapolitanaKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_NapolitanaKeyTyped

    private void MargaritaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MargaritaKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MargaritaKeyTyped

    private void FriesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FriesKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_FriesKeyTyped

    private void CreamyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CreamyKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CreamyKeyTyped

    private void MayoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MayoKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MayoKeyTyped

    private void ColaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ColaKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ColaKeyTyped

    private void PepsiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PepsiKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_PepsiKeyTyped

    private void FantaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FantaKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_FantaKeyTyped

    private void OrangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OrangeKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_OrangeKeyTyped

    private void BisqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BisqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BisqueActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzeria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bisque;
    private javax.swing.JTextField Burata;
    private javax.swing.JTextField Cash;
    private javax.swing.JTextField Change;
    private javax.swing.JCheckBox ChkBisque;
    private javax.swing.JCheckBox ChkBurata;
    private javax.swing.JCheckBox ChkCola;
    private javax.swing.JCheckBox ChkCreamy;
    private javax.swing.JCheckBox ChkFanta;
    private javax.swing.JCheckBox ChkFries;
    private javax.swing.JCheckBox ChkGrill;
    private javax.swing.JCheckBox ChkJosper;
    private javax.swing.JCheckBox ChkMargarita;
    private javax.swing.JCheckBox ChkMayo;
    private javax.swing.JCheckBox ChkNapolitana;
    private javax.swing.JCheckBox ChkNicoise;
    private javax.swing.JCheckBox ChkOrange;
    private javax.swing.JCheckBox ChkPepper;
    private javax.swing.JCheckBox ChkPepsi;
    private javax.swing.JCheckBox ChkSoup;
    private javax.swing.JTextField Cola;
    private javax.swing.JTextField Creamy;
    private javax.swing.JTextField Fanta;
    private javax.swing.JTextField Fries;
    private javax.swing.JTextField Grill;
    private javax.swing.JTextField Josper;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JTextField Margarita;
    private javax.swing.JTextField Mayo;
    private javax.swing.JTextField Napolitana;
    private javax.swing.JTextField Nicoise;
    private javax.swing.JTextField Orange;
    private javax.swing.JTextField Pepper;
    private javax.swing.JTextField Pepsi;
    private javax.swing.JTextField Soup;
    private javax.swing.JButton bTotal;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel cmbPaymentMethod;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTax;
    private javax.swing.JTextField jlblSubTotal;
    private javax.swing.JTextField jlblTotal;
    // End of variables declaration//GEN-END:variables

}
